import { type NextPage } from "next";
import Head from "next/head";
import { useState, useCallback } from "react";
import debounce from "lodash.debounce";

import { trpc } from "../utils/trpc";
import type { RouterOutputs } from "../utils/trpc";
import TextEditor from "../components/editor/TextEditor";
import NotesList from "../components/NotesList";

type Note = RouterOutputs["notes"]["getAll"][number] | undefined;

const Home: NextPage = () => {

  const [currentNote, setCurrentNote] = useState<Note>(undefined);

  const notes = trpc.notes.getAll.useQuery(undefined, {
    refetchOnWindowFocus: false,
  });

  const create = trpc.notes.create.useMutation({
    onSuccess: () => {
      notes.refetch();
    }
  }
  );

  const updateNote = trpc.notes.update.useMutation({
    onSuccess: () => {
      notes.refetch();
    }
  });

  const deleteNote = trpc.notes.delete.useMutation({
    onSuccess: () => {
      notes.refetch();
    }
  });

  const debounceApiCall = useCallback( 
    debounce((noteId: string, title: string, content: string) => {
      updateNote.mutate({ id: noteId, title, content });
    }, 1000), []);

  const updateEditor = (noteId: string) => {
    const note = notes.data?.find((note) => note.id === noteId);
    setCurrentNote(note);
  }

  const handleDelete = (id: string) => {
    deleteNote.mutate({ id });
    setCurrentNote(undefined);
  }

  return (
    <>
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full p-5 font-mono gap-5">
        <NotesList updateEditor={updateEditor} notes={notes.data}  createNote={() => create.mutate({ title: "Untitled", content: "" })} />
        <TextEditor debounceApiCall={debounceApiCall} note={currentNote} deleteNote={handleDelete} />
      </main>
    </>
  );
};

export default Home;
