import { type NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const notes = trpc.notes.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="">Notes</h1>
        <ul>
          {notes.data?.map((note) => (
            <li key={note.id}>{note.title}</li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
